name: Automatically concatenate new url yaml with existing one

on:
  push:
    branches:
      - gh-pages
    paths:
      - _data/newurl.yml

jobs:
  validate_and_concatenate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: 'gh-pages'

    - name: Install yamllint
      run: |
        sudo apt-get update
        sudo apt-get install -y yamllint

    - name: Validate individual YML files
      run: 'yamllint -d "{extends: relaxed, rules: {line-length: {max: 180}}}" _data/newurl.yml _data/urls.yml'

    - name: Concatenate YAML files (newurl at the start of urls)
      run: |
        tail -n +2 _data/urls.yml > _data/temp.yml
        cat _data/newurl.yml _data/temp.yml > _data/urls.yml

    - name: Validate concatenated YML file
      run: 'yamllint -d "{extends: relaxed, rules: {line-length: {max: 180}}}" _data/urls.yml'

    - name: Commit concatenated file
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git rm _data/newurl.yml
        git add _data/urls.yml
        git commit -m 'Automatically added new url ...'
        git push