# this action is related to gh-pages branch ... but as GH doesn't register workflows that are workflow_dispatch only on the main branch, had to put it here

name: "Add book json to json file from Apple shortcut"

on:
  workflow_dispatch:
    inputs:
      json_content:
        description: 'JSON content to append'
        required: true
        type: string
      target_file:
        description: 'target file'
        required: false
        default: '_data/books.json'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  append:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Append JSON to file
        run: |
          mkdir -p "$(dirname "${{ inputs.target_file }}")"
          echo '${{ inputs.json_content }}' >> "${{ inputs.target_file }}"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ inputs.target_file }}"
          git commit -m "Append JSON entry from Shortcuts"
          git push
