name: Send Telegram Message

on:
  push

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Commit Details
      id: commit-info
      run: |
        # Extract commit details
        echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV

    - name: Send Telegram message
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        COMMIT_AUTHOR: ${{ env.COMMIT_AUTHOR }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_API_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d parse_mode="Markdown" \
          -d text="🚀 New commit pushed to your repository! *Author*: \`${COMMIT_AUTHOR}\` *Message*: \`${COMMIT_MESSAGE}\`"
