name: Send Telegram Message

on:
  push

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Commit Details
      id: commit-info
      run: |
        # Extract commit details
        echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
        # Extract and sanitize the diff content
        DIFF_CONTENT=$(git show --no-color --oneline   | sed 's/|/-/g')
        echo "COMMIT_DIFF=${DIFF_CONTENT}" >> $GITHUB_ENV

    - name: Send Telegram message
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        COMMIT_AUTHOR: ${{ env.COMMIT_AUTHOR }}
      run: |
        # Truncate the diff content to fit Telegram's message size limit (4096 characters)
        TRUNCATED_DIFF=$(echo "${COMMIT_DIFF}" | head -c 2000)

        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_API_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d parse_mode="Markdown" \
          -d text="🚀 New commit pushed to *main* branch!\n\n*Author*: ${COMMIT_AUTHOR}\n*Message*: ${COMMIT_MESSAGE}\n\n*Changes:*\n\`\`\`\n${TRUNCATED_DIFF}\n\`\`\`"
