name: Send Telegram Message

on:
  push

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Commit Details
      id: commit-info
      run: |
        # Extract commit details
        echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
        COMMIT_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
        echo "COMMIT_URL=${COMMIT_URL}" >> $GITHUB_ENV
        # Extract and sanitize the diff content
        git show --no-color --pretty=format:'%b' --unified=0 --stat | sed 's/|/-/g' | head -n 200 > commit_diff.txt

    - name: Get Branch Name
      id: branch-name
      run: |
        # Extract the branch name from GITHUB_REF
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

    - name: Send Telegram message
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        COMMIT_DIFF$(cat commit_diff.txt)
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_API_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d parse_mode="Markdown" \
          -d text="🚀 New commit pushed to your repository in *${BRANCH_NAME}*.\u0D *Author*: \`${COMMIT_AUTHOR}\`\u0D *Message*: \`${COMMIT_MESSAGE}\` [View Commit](${COMMIT_URL}). *Changes:* \`\`\`${COMMIT_DIFF}\`\`\`"
